block_shape.o : block_shape.c
	gcc -fPIC -c block_shape.c -I../header_ih
drop.o : drop.c
	gcc -fPIC -c drop.c -I../header_ih
collision.o : collision.c
	gcc -fPIC -c collision.c -I../header_ih
move_block.o : move_block.c
	gcc -fPIC -c move_block.c -I../header_ih
clean :
	rm *.o

