libfuncs.a : background_screen.o line_clear.o level_up_check.o display_tetris.o
	ar rv libfuncs.a background_screen.o line_clear.o level_up_check.o display_tetris.o

background_screen.o : background_screen.c 
	gcc -c background_screen.c -I../header_yj -I../../kih/header_ih

line_clear.o : line_clear.c 
	gcc -c line_clear.c -I../header_yjchar i_block[4][4][4];

char t_block[4][4][4];

char s_block[4][4][4];

char z_block[4][4][4];

char l_block[4][4][4];

char j_block[4][4][4];



extern int x; // Block -> x

extern int y; // Block -> y

extern int block_state; // block rotate state

extern int block_number;

extern int next_block_number;

extern long point;

level_up_check.o : level_up_check.c 
	gcc -c level_up_check.c -I../header_yj

display_tetris.o : display_tetris.c
	gcc -c display_tetris.c -I../header_yj


clean :
	rm  *.o *.a
